[debug] [2021-07-29T04:38:53.833Z] ----------------------------------------------------------------------
[debug] [2021-07-29T04:38:53.835Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js projects:create app-to-date
[debug] [2021-07-29T04:38:53.835Z] CLI Version:   9.16.0
[debug] [2021-07-29T04:38:53.836Z] Platform:      win32
[debug] [2021-07-29T04:38:53.836Z] Node Version:  v14.17.0
[debug] [2021-07-29T04:38:53.837Z] Time:          Thu Jul 29 2021 11:38:53 GMT+0700 (Western Indonesia Time)
[debug] [2021-07-29T04:38:53.837Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-07-29T04:38:53.840Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2021-07-29T04:38:53.861Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-07-29T04:38:53.862Z] > authorizing via signed-in user (muttaqinimam76@gmail.com)
[debug] [2021-07-29T04:38:54.770Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2021-07-29T04:38:54.770Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2021-07-29T04:38:57.728Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-07-29T04:38:57.729Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-07-29T04:38:57.837Z] <<< HTTP RESPONSE 200 {"date":"Thu, 29 Jul 2021 04:38:57 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-07-29T04:38:57.851Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects  
 {"projectId":"app-to-date","name":"app-to-date"}
[debug] [2021-07-29T04:38:58.964Z] <<< HTTP RESPONSE 409 {"vary":"X-Origin, Referer, Origin,Accept-Encoding","content-type":"application/json; charset=UTF-8","date":"Thu, 29 Jul 2021 04:38:58 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=999","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-07-29T04:38:58.964Z] <<< HTTP RESPONSE BODY {"error":{"code":409,"message":"Requested entity already exists","status":"ALREADY_EXISTS"}}
[debug] [2021-07-29T04:38:58.967Z] FirebaseError: HTTP Error: 409, Requested entity already exists
    at module.exports (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:38:12)
    at Request._callback (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\lib\api.js:41:35)
    at Request.self.callback (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:185:22)
    at Request.emit (events.js:376:20)
    at Request.emit (domain.js:470:12)
    at Request.<anonymous> (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:376:20)
    at Request.emit (domain.js:470:12)
    at IncomingMessage.<anonymous> (C:\Users\ASUS\AppData\Roaming\npm\node_modules\firebase-tools\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:482:28)
    at IncomingMessage.emit (events.js:388:22)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[error] 
[error] Error: Failed to create project because there is already a project with ID app-to-date. Please try again with a unique project ID.
